have_fun: false
code_review:
  disable: false
  comment_severity_threshold: HIGH
  max_review_comments: 10
  pull_request_opened:
    help: false
    summary: true
    code_review: true
  pull_request_updated:
    help: false
    summary: false
    code_review: true